In [ ]:
WORKING WITH NUMPY ARRAYS

#1)Converting list to array

In [2]:
import numpy as np
l1 = [1, 2, 3, 4, 5]
a = np.array(l1)
print(a)
print(type(a))
arr=np.array(l1,ndmin=1)
print(arr)
arr=np.array(l1,ndmin=2)
print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
[[1 2 3 4 5]]


#2)Arange Function

In [3]:
a=np.arange(1,10)
print(a)#[1 2 3 4 5 6 7 8 9]                

[1 2 3 4 5 6 7 8 9]


#3)Multidimensional Array

In [4]:
l1=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print(np.array(l1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#4)Size function

In [5]:
arr=np.array(l1)
b=arr.size#12
print(b)
print("Total :",arr.size)
print("Rows :",np.size(arr,0))
print("Columns :",np.size(arr,1))
print(np.size(arr))

12
Total : 12
Rows : 4
Columns : 3
12


#5)Shape Function

In [6]:
print(arr.shape)                                   

(4, 3)


#6)Dtype

In [7]:
print(arr.dtype)#int32                                       

int64


#7)Ndim Function

In [8]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1.ndim)#1
print(arr2.ndim)#2                          

1
2


#8)Zeroes function

In [9]:
a=np.zeros(shape=(3,5),dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#9)Ones Function

In [10]:
a=np.ones((3,5),dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#10)Eye Function

In [11]:
a=np.eye(2,dtype=int)
print(a)

[[1 0]
 [0 1]]


#11)Empty Function

In [15]:
a=np.empty(shape=(5,5))
print(a)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.02360528e-306
  1.89146896e-307]
 [7.56571288e-307 3.11525958e-307 1.24610723e-306 1.37962320e-306
  1.29060871e-306]
 [2.22518251e-306 1.33511969e-306 1.78022342e-306 1.05700345e-307
  3.11525958e-307]
 [1.69118108e-306 8.06632139e-308 1.20160711e-306 1.69119330e-306
  1.29062229e-306]
 [1.24610383e-306 6.89804132e-307 1.69121096e-306 8.34449382e-308
  3.91792476e-317]]


#12)Random Functions

In [23]:
a=np.random.rand(3,4)
print(a)#range is from 0 to 1
print("*"*50)
a=np.random.randint(low=1,high=10,size=10)
print(a)#[7 2 9 4 7 1 2 1 4 3]
print("*"*50)
a=np.random.randn(100)
print(a)#generally between -1 to 1

[[0.49120313 0.67480993 0.79085418 0.98268749]
 [0.08408068 0.63121211 0.5769749  0.65064218]
 [0.54317945 0.55736739 0.86855463 0.45201162]]
**************************************************
[9 1 7 9 4 8 2 9 3 9]
**************************************************
[ 1.25315098  0.27158045  0.98768745 -0.03352928  1.4594122  -0.6260932
  2.10780181  0.89805593  0.19170972 -0.10059093 -0.54162819  0.41210651
  0.14951691  0.01128928 -0.10067408 -0.23023787  0.46496484  1.56212729
  0.37007671  1.68688756 -0.17652936  0.50500309 -0.60345071  0.10003706
 -2.13670184  1.41637768 -0.19494764 -0.24067623  0.33601784  1.7280586
 -2.1644261   2.13160933 -1.33481003  0.32040639 -0.1407898   0.78043054
 -1.23981775  0.49830881 -1.17526863 -1.30327927 -0.28830829 -0.06351179
 -1.00079185  0.48627021  1.62435725  1.40321161 -1.07919619  1.02647794
  1.00185936 -0.81538421 -1.06777578 -0.34342124 -0.34221622  0.63665726
  0.23409143 -0.05782493  1.71503601 -0.50306832  0.80173409 -0.16986612
 -0.15

#13)Reshape Function-Will not alter the original data

In [25]:
a=np.random.randint(1,15,(3,4))
print(a)
print(a.shape)
print("*"*5)
a=a.reshape(4,3)
print(a)
#elements must be sufficient for reshaping

[[10 14  3 10]
 [ 2 12  2  2]
 [13  7  9  4]]
(3, 4)
*****
[[10 14  3]
 [10  2 12]
 [ 2  2 13]
 [ 7  9  4]]


#14)Linspace Function

In [26]:
a=np.linspace(1,10,5)
print(a)#[ 1.    3.25  5.5   7.75 10.  ],start,stop,and numbers

[ 1.    3.25  5.5   7.75 10.  ]


#15)Flatten Function

In [27]:
a=np.random.randint(1,15,(3,4))
print(a.shape)
print(a)
a=a.flatten()
print(a.shape)
print(a)#Flattens it in a single line

(3, 4)
[[ 3 11 10 14]
 [ 6 10  4  3]
 [14  7  2  4]]
(12,)
[ 3 11 10 14  6 10  4  3 14  7  2  4]


#16)Logspace

In [28]:
a=np.logspace(2,4,10,base=2)
print(a)#simlar to linespace

[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]


#17)Copy Function

In [29]:
a1=np.random.randint(1,10,10);
a2=a1
print(a1,id(a1))
print(a2,id(a2))#Both are same and have same id
a1=np.random.randint(1,10,10);
a2=np.copy(a1)
print(a1,id(a1))
print(a2,id(a2))#Both are same but different id's

[3 4 4 8 2 4 8 4 7 9] 2025172599120
[3 4 4 8 2 4 8 4 7 9] 2025172599120
[6 1 1 6 6 5 9 8 7 2] 2025544777040
[6 1 1 6 6 5 9 8 7 2] 2025544777328


#18)arr.max(),arr.min(),arr.sum() functions

In [31]:
a=np.random.randint(1,15,(3,5))
print(a)
# Max: 13
# Min: 1
# Sum: 104
print("*"*10)
print("Max:",a.max())
print("Min:",a.min())
print("Sum:",a.sum())
 #FOR COLUMNS
print("*"*10)
print("Max:",a.max(axis=0))
print("Min:",a.min(axis=0))
print("Sum:",a.sum(axis=0))
 #FOR ROWS
print("*"*10)
print("Max:",a.max(axis=1))
print("Min:",a.min(axis=1))
print("Sum:",a.sum(axis=1))

[[ 5 12  9 13 14]
 [12  5  3  7  1]
 [ 3 10  1  9  2]]
**********
Max: 14
Min: 1
Sum: 106
**********
Max: [12 12  9 13 14]
Min: [3 5 1 7 1]
Sum: [20 27 13 29 17]
**********
Max: [14 12 10]
Min: [5 1 1]
Sum: [53 28 25]


#19)Seed Function

In [32]:
a=np.random.seed(3)
arr=np.random.randint(1,10,(3,5))
print(arr)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]


#20)Sorting function

In [33]:
a=np.random.randint(1,10,(3,5))
b=np.sort(a,axis=0)
c=np.sort(a,axis=1,kind="mergesort")
print(b)
print(c)
d=b.flatten()
print(d)
e=np.sort(d)
##RESHAPING
f=np.reshape(np.sort(a.flatten()),a.shape)
print(f)
##(KIND) IS USED TO DEFINE meresort,quicksort

[[6 2 1 2 4]
 [7 3 2 6 5]
 [9 9 3 9 8]]
[[2 3 3 4 7]
 [2 6 8 9 9]
 [1 2 5 6 9]]
[6 2 1 2 4 7 3 2 6 5 9 9 3 9 8]
[[1 2 2 2 3]
 [3 4 5 6 6]
 [7 8 9 9 9]]


#21)Mathematical Operations

In [34]:
#a)Addition
a=np.random.seed(3)
arr=np.random.randint(1,10,(3,5))
print(arr+1)
#b)Subtraction
print(arr-1)
#c)Multiplication
print(arr*2)
#d)Division
print(arr/2)
#5)Floor Division
print(arr//2)
#6)Matrix Multiplication-------------------------------------------------------
arr1=np.random.randint(1,10,(2,2))
arr2=np.random.randint(1,10,(2,2))
print(arr1)
print(arr2)
print(arr1*arr2)
print(arr1.dot(arr2))
#7)Power
print(arr1)
print(arr1**2)

[[10  5 10 10  2]
 [ 7  5  7  9  8]
 [ 2  6  9 10  3]]
[[8 3 8 8 0]
 [5 3 5 7 6]
 [0 4 7 8 1]]
[[18  8 18 18  2]
 [12  8 12 16 14]
 [ 2 10 16 18  4]]
[[4.5 2.  4.5 4.5 0.5]
 [3.  2.  3.  4.  3.5]
 [0.5 2.5 4.  4.5 1. ]]
[[4 2 4 4 0]
 [3 2 3 4 3]
 [0 2 4 4 1]]
[[7 3]
 [3 2]]
[[4 6]
 [9 2]]
[[28 18]
 [27  4]]
[[55 48]
 [30 22]]
[[7 3]
 [3 2]]
[[49  9]
 [ 9  4]]


#22)Percentile Function

In [20]:
np.random.seed(3)
arr=np.random.randint(1,10,10)
print(arr)
arr=np.sort(arr)
print(np.percentile(arr,50))       

[9 4 9 9 1 6 4 6 8 7]
6.5


#23)Mean,Variance and Standard deviation

In [19]:
np.random.seed(3)
a=np.random.randint(120,200,10)
print(a)
print(a.mean())
print(a.var())
print(a.std())

[144 123 176 192 120 141 139 194 161 130]
152.0
672.4
25.93067681338071


#24)Filtering an numpy array

In [18]:
arr=np.arange(1,10)
print(arr)
print(arr>5)
arr2=arr[arr>5]
print(arr2)
arr[arr>5]=10
print(arr)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
[ 1  2  3  4  5 10 10 10 10]


#25)Transposing an array

In [17]:
a=np.random.randint(1,10,(2,3))
print(a)
b=a.T
print(b)
print(b.shape)                     

[[8 2 1]
 [1 6 9]]
[[8 1]
 [2 6]
 [1 9]]
(3, 2)


#26)Where Function

In [16]:
arr=np.random.randint(1,100,10)
print(arr)
print(np.where(arr%2==0,100,arr))

[ 2 19 64  3 88 21 63 82 23 93]
[100  19 100   3 100  21  63 100  23  93]


#27)Merging arrays

In [14]:
a1=np.random.randint(1,10,(2,4))
a2=np.random.randint(1,10,(2,4))
print(a1)
print(a2)
print("*"*40)
print(np.concatenate((a1,a2),axis=0))
print(np.concatenate((a1,a2),axis=1))
#VStack and HStack
print("*"*40)
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

[[9 8 5 1]
 [1 5 4 1]]
[[9 3 8 3]
 [2 4 3 5]]
****************************************
[[9 8 5 1]
 [1 5 4 1]
 [9 3 8 3]
 [2 4 3 5]]
[[9 8 5 1 9 3 8 3]
 [1 5 4 1 2 4 3 5]]
****************************************
[[9 8 5 1]
 [1 5 4 1]
 [9 3 8 3]
 [2 4 3 5]]
[[9 8 5 1 9 3 8 3]
 [1 5 4 1 2 4 3 5]]


#28)Splitting the arrays

In [12]:
a=np.random.randint(1,10,(4,4))
print(np.vsplit(a,2))
print(np.hsplit(a,2))

[array([[4, 1, 1, 1],
       [1, 3, 3, 8]], dtype=int32), array([[1, 6, 1, 2],
       [5, 2, 3, 3]], dtype=int32)]
[array([[4, 1],
       [1, 3],
       [1, 6],
       [5, 2]], dtype=int32), array([[1, 1],
       [3, 8],
       [1, 2],
       [3, 3]], dtype=int32)]
